name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test-on-macos-11:
    name: Test on macOS 11
    runs-on: macOS-11
    strategy:
      matrix:
        xcode: ["12.4", "12.5.1", "13.0"]
    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          .build/artifacts
          .build/checkouts
          .build/repositories
        key: ${{ runner.os }}-dependencies-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-${{ matrix.xcode }}-
          ${{ runner.os }}-dependencies-
          ${{ runner.os }}-

    - name: Select Xcode
      run: |
        xcodebuild -version
        ls -nt /Applications/ | grep "Xcode*"
        sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
        xcodebuild -version

    - name: Install danger-js
      run: brew install danger/tap/danger-js

    - run: swift test

    - run: swift run danger-swift ci --verbose --failOnErrors
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-on-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["5.3.3"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          .build/artifacts
          .build/checkouts
          .build/repositories
        key: ${{ runner.os }}-dependencies-${{ matrix.swift }}-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-${{ matrix.swift }}-
          ${{ runner.os }}-dependencies-
          ${{ runner.os }}-

    - name: Install danger-js
      run: |
        yarn global add danger
        echo `yarn global bin` >> $GITHUB_PATH

    - run: echo ${{ matrix.swift }} > .swift-version

    - uses: YOCKOW/Action-setup-swift@v1

    - run: swift test

    - run: swift run danger-swift ci --verbose --failOnErrors
      if: ${{ github.event_name == 'pull_request' }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  test-without-spm-on-macos-11:
    name: Test without SPM on macOS 11
    runs-on: macOS-11
    strategy:
      matrix:
        xcode: ["12.4", "12.5.1", "13.0"]
    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          .build/artifacts
          .build/checkouts
          .build/repositories
        key: ${{ runner.os }}-without-spm-package-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-without-spm-package-${{ matrix.xcode }}-
          ${{ runner.os }}-without-spm-package-
          ${{ runner.os }}-

    - name: Select Xcode
      run: |
        xcodebuild -version
        ls -nt /Applications/ | grep "Xcode*"
        sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
        xcodebuild -version

    - name: Install danger-js
      run: brew install danger/tap/danger-js

    - run: make install

    - run: danger-swift ci --verbose --failOnErrors
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-without-spm-on-linux:
    name: Test without SPM on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["5.3.3"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          .build/artifacts
          .build/checkouts
          .build/repositories
        key: ${{ runner.os }}-without-spm-package-${{ matrix.swift }}-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-without-spm-package-${{ matrix.swift }}-
          ${{ runner.os }}-without-spm-package-
          ${{ runner.os }}-

    - name: Install danger-js
      run: |
        yarn global add danger
        echo `yarn global bin` >> $GITHUB_PATH

    - run: echo ${{ matrix.swift }} > .swift-version

    - uses: YOCKOW/Action-setup-swift@v1
    
    - run: sudo chmod -R a+rwx /usr/local

    - run: make install

    - run: danger-swift ci --verbose --failOnErrors
      if: ${{ github.event_name == 'pull_request' }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
